<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* This file handles pages, but only exists for the sake of child theme forward compatibility.


$custom_query = new WP_Query(array(
        'cat' => 'Product',
        'posts_per_page' => 100,
        'paged' => (get_query_var('paged')) ? get_query_var('paged') : 1
    ));

genesis();